spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: xuxiaolei
    virtual-host: /
    publisher-confirm-type: CORRELATED # 交换机的确认
    publisher-returns: true # 队列的确认